// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNNOgAOj1cbvT5-gYp00YlneSZ9ZypfE',
    appId: '1:493787940567:web:3c5f44305b587affd85292',
    messagingSenderId: '493787940567',
    projectId: 'flutter-chat-app-6857a',
    authDomain: 'flutter-chat-app-6857a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6857a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSMsDvfoLiBIZMFGXgWgWvUm_Uz8C5Gk',
    appId: '1:493787940567:android:b191d3eb2f18cf05d85292',
    messagingSenderId: '493787940567',
    projectId: 'flutter-chat-app-6857a',
    storageBucket: 'flutter-chat-app-6857a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKVjVUJSJ8tCFwX75igRQYfwS6BTCgEyU',
    appId: '1:493787940567:ios:65debcfb421766a8d85292',
    messagingSenderId: '493787940567',
    projectId: 'flutter-chat-app-6857a',
    storageBucket: 'flutter-chat-app-6857a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKVjVUJSJ8tCFwX75igRQYfwS6BTCgEyU',
    appId: '1:493787940567:ios:f32cc51219962109d85292',
    messagingSenderId: '493787940567',
    projectId: 'flutter-chat-app-6857a',
    storageBucket: 'flutter-chat-app-6857a.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
